// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.DbContexts;

#nullable disable

namespace SematecCC.Infra.Migrations
{
    [DbContext(typeof(SematecCCDbContext))]
    [Migration("20260523070259_initialDb_14050302")]
    partial class initialDb_14050302
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SematecCC.Core.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("CardNo")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<int>("CardOrderId")
                        .HasColumnType("int");

                    b.Property<int>("CardTypeId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("date");

                    b.Property<string>("ExpireDateFa")
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<int?>("OwnerPersonId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<decimal>("RemainedAmount")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("SerialNo")
                        .IsRequired()
                        .HasColumnType("varchar(7)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasComment(" \r\n1:اولیه\r\n2:تایید شده\r\n3:لغو شده");

                    b.Property<int?>("UserIdChanged")
                        .HasColumnType("int");

                    b.Property<int>("UserIdCreated")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CardNo")
                        .IsUnique()
                        .HasDatabaseName("IX_Cards_CardNo_Unique");

                    b.HasIndex("CardOrderId");

                    b.HasIndex("CardTypeId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("OwnerPersonId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("SematecCC.Core.CardOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("date");

                    b.Property<string>("ExpireDateFa")
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("ExpireDayNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasComment("\r\n1:اولیه \r\n2:تایید شده\r\n3:لغو شده ");

                    b.Property<int>("Tedad")
                        .HasColumnType("int");

                    b.Property<int?>("UserIdChanged")
                        .HasColumnType("int");

                    b.Property<int>("UserIdCreated")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("CardOrders");
                });

            modelBuilder.Entity("SematecCC.Core.CardTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("BranchId")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<int>("CardTransactionTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ProviderId")
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("RemainedAmount")
                        .HasColumnType("decimal(18,3)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasComment(" \r\n1:اولیه\r\n2:تایید شده \r\n3:منقضی شده \r\n4:مرجوع شده");

                    b.Property<string>("TerminalId")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UserIdChanged")
                        .HasColumnType("int");

                    b.Property<int>("UserIdCreated")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("CardTransactionTypeId");

                    b.HasIndex("ProviderId")
                        .HasDatabaseName("UX_CardTransaction_ProviderId");

                    b.ToTable("CardTransactions");
                });

            modelBuilder.Entity("SematecCC.Core.CardTransactionType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<short>("Sign")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UserIdChanged")
                        .HasColumnType("int");

                    b.Property<int>("UserIdCreated")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CardTransactionTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2026, 5, 23, 10, 32, 58, 816, DateTimeKind.Local).AddTicks(9901),
                            Sign = (short)1,
                            Title = "شارژ اولیه",
                            UserIdCreated = 1
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2026, 5, 23, 10, 32, 58, 816, DateTimeKind.Local).AddTicks(9904),
                            Sign = (short)-1,
                            Title = "خرج کردن",
                            UserIdCreated = 1
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2026, 5, 23, 10, 32, 58, 816, DateTimeKind.Local).AddTicks(9906),
                            Sign = (short)1,
                            Title = "افزایش دستی اعتبار کارت ",
                            UserIdCreated = 1
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2026, 5, 23, 10, 32, 58, 816, DateTimeKind.Local).AddTicks(9907),
                            Sign = (short)-1,
                            Title = "کاهش دستی اعتبار کارت ",
                            UserIdCreated = 1
                        },
                        new
                        {
                            Id = 5,
                            DateCreated = new DateTime(2026, 5, 23, 10, 32, 58, 816, DateTimeKind.Local).AddTicks(9909),
                            Sign = (short)1,
                            Title = "افزایش تراکنش لغو شده",
                            UserIdCreated = 1
                        },
                        new
                        {
                            Id = 6,
                            DateCreated = new DateTime(2026, 5, 23, 10, 32, 58, 816, DateTimeKind.Local).AddTicks(9911),
                            Sign = (short)1,
                            Title = "افزایش تراکنش منقضی شده",
                            UserIdCreated = 1
                        },
                        new
                        {
                            Id = 7,
                            DateCreated = new DateTime(2026, 5, 23, 10, 32, 58, 816, DateTimeKind.Local).AddTicks(9913),
                            Sign = (short)1,
                            Title = "افزایش اعتبار کارت از طریق Api",
                            UserIdCreated = 1
                        });
                });

            modelBuilder.Entity("SematecCC.Core.CardType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsChargeable")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UserIdChanged")
                        .HasColumnType("int");

                    b.Property<int>("UserIdCreated")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CardTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2026, 5, 23, 10, 32, 58, 817, DateTimeKind.Local).AddTicks(1563),
                            IsChargeable = false,
                            Title = "کارت هدیه",
                            UserIdCreated = 1
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2026, 5, 23, 10, 32, 58, 817, DateTimeKind.Local).AddTicks(1565),
                            IsChargeable = false,
                            Title = "کارت باشگاه مشتریان ",
                            UserIdCreated = 1
                        });
                });

            modelBuilder.Entity("SematecCC.Core.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiPassword")
                        .HasMaxLength(656)
                        .HasColumnType("nvarchar(656)");

                    b.Property<string>("ApiUsername")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ClientID")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("ClientSecret")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("UserIdChanged")
                        .HasColumnType("int");

                    b.Property<int>("UserIdCreated")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyCode")
                        .IsUnique()
                        .HasDatabaseName("IX_Companies_CompanyCode_Unique");

                    b.HasIndex("CompanyName")
                        .IsUnique()
                        .HasDatabaseName("IX_Companies_CompanyName_Unique");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyCode = "01307816",
                            CompanyName = "شرکت گیو",
                            DateCreated = new DateTime(2026, 5, 23, 10, 32, 58, 755, DateTimeKind.Local).AddTicks(5164),
                            UserIdCreated = 1
                        });
                });

            modelBuilder.Entity("SematecCC.Core.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("UserIdChanged")
                        .HasColumnType("int");

                    b.Property<int>("UserIdCreated")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Customers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2026, 5, 23, 10, 32, 58, 755, DateTimeKind.Local).AddTicks(4988),
                            FirstName = "مهران",
                            LastName = "صرافی",
                            NationalCode = "1234567890",
                            UserIdCreated = 1
                        });
                });

            modelBuilder.Entity("SematecCC.Core.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateDone")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<byte>("OperationId")
                        .HasColumnType("tinyint")
                        .HasComment("\r\n1:تایید سفارش کارت \r\n2:لغو سفارش کارت \r\n3:غیرفعال کردن کارت \r\n4:فعال کردن کارت \r\n5:تعیین مالک کارت \r\n6: افزایش دستی اعتبار کارت \r\n7: کاهش دستی اعتبار کارت \r\n");

                    b.Property<int>("RecordId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("SematecCC.Core.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Mobile")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telephone")
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("UserIdChanged")
                        .HasColumnType("int");

                    b.Property<int>("UserIdCreated")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationName")
                        .IsUnique()
                        .HasDatabaseName("UI_Organization_OrganizationName");

                    b.ToTable("Organizations", (string)null);
                });

            modelBuilder.Entity("SematecCC.Core.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("BirthDateFa")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("GivId")
                        .HasColumnType("bigint")
                        .HasComment("UX_GivId_CompanyId: GivId is unique per company\nX_Company_Mobile: (GivId, CompanyId, Mobile) are indexed. For every company must be ONE Mobile registered and given one givId , but with api and offline data gathered its violation is possible.");

                    b.Property<string>("JobPlace")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NationalCode")
                        .HasColumnType("varchar(13)");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("UserIdChanged")
                        .HasColumnType("int");

                    b.Property<int>("UserIdCreated")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Mobile")
                        .HasDatabaseName("X_Company_Mobile");

                    b.HasIndex("GivId", "CompanyId")
                        .IsUnique()
                        .HasDatabaseName("UX_GivId_CompanyId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("SematecCC.Infra.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            Name = "companyAdmin",
                            NormalizedName = "COMPANYADMIN"
                        },
                        new
                        {
                            Id = 3,
                            Name = "companyUser",
                            NormalizedName = "COMPANYUser"
                        });
                });

            modelBuilder.Entity("SematecCC.Infra.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(656)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(656)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(656)");

                    b.Property<string>("Telephone")
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            CompanyId = 1,
                            ConcurrencyStamp = "991fb354-16d2-40e8-918d-4b7af7d8ba91",
                            Email = "admin@givsoft.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LastName = "admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GIVSOFT.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEOCYUC6sO534Zgchx65AABYW4HQJ3xxShUGPblk8RGHrpq/o+7idVuwAmcyn5xA82Q==",
                            PhoneNumber = "09121307816",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "a0dc8c2f-fe56-4c6b-9680-46f2ad21d8ca",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SematecCC.Core.Card", b =>
                {
                    b.HasOne("SematecCC.Core.CardOrder", "CardOrder")
                        .WithMany("Cards")
                        .HasForeignKey("CardOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SematecCC.Core.CardType", "CardType")
                        .WithMany()
                        .HasForeignKey("CardTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SematecCC.Core.Company", "Company")
                        .WithMany("Cards")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SematecCC.Core.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId");

                    b.HasOne("SematecCC.Core.Person", "Owner")
                        .WithMany("Cards")
                        .HasForeignKey("OwnerPersonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CardOrder");

                    b.Navigation("CardType");

                    b.Navigation("Company");

                    b.Navigation("Organization");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("SematecCC.Core.CardOrder", b =>
                {
                    b.HasOne("SematecCC.Core.Company", "Company")
                        .WithMany("CardOrders")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SematecCC.Core.Organization", "Organization")
                        .WithMany("CardOrders")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("SematecCC.Core.CardTransaction", b =>
                {
                    b.HasOne("SematecCC.Core.Card", "Card")
                        .WithMany("CardTransactions")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SematecCC.Core.CardTransactionType", "CardTransactionType")
                        .WithMany("CardTransactions")
                        .HasForeignKey("CardTransactionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("CardTransactionType");
                });

            modelBuilder.Entity("SematecCC.Core.Person", b =>
                {
                    b.HasOne("SematecCC.Core.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("SematecCC.Infra.ApplicationUser", b =>
                {
                    b.HasOne("SematecCC.Core.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("SematecCC.Infra.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("SematecCC.Infra.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("SematecCC.Infra.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("SematecCC.Infra.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SematecCC.Infra.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("SematecCC.Infra.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SematecCC.Core.Card", b =>
                {
                    b.Navigation("CardTransactions");
                });

            modelBuilder.Entity("SematecCC.Core.CardOrder", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("SematecCC.Core.CardTransactionType", b =>
                {
                    b.Navigation("CardTransactions");
                });

            modelBuilder.Entity("SematecCC.Core.Company", b =>
                {
                    b.Navigation("CardOrders");

                    b.Navigation("Cards");
                });

            modelBuilder.Entity("SematecCC.Core.Organization", b =>
                {
                    b.Navigation("CardOrders");
                });

            modelBuilder.Entity("SematecCC.Core.Person", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
