// <auto-generated />
using System;
using SematecCC.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SematecCC.Infra.Migrations
{
    [DbContext(typeof(SematecCCDbContext))]
    [Migration("20260614121437_addPermissionsAndMenuTables")]
    partial class addPermissionsAndMenuTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SematecCC.Core.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("CardNo")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<int>("CardOrderId")
                        .HasColumnType("int");

                    b.Property<int>("CardTypeId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("date");

                    b.Property<string>("ExpireDateFa")
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<int?>("OwnerPersonId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<decimal>("RemainedAmount")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("SerialNo")
                        .IsRequired()
                        .HasColumnType("varchar(7)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasComment(" \r\n                    1:اولیه\r\n                    2:تایید شده\r\n                    3:لغو شده");

                    b.Property<int?>("UserIdChanged")
                        .HasColumnType("int");

                    b.Property<int>("UserIdCreated")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CardNo")
                        .IsUnique()
                        .HasDatabaseName("IX_Cards_CardNo_Unique");

                    b.HasIndex("CardOrderId");

                    b.HasIndex("CardTypeId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("OwnerPersonId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("SematecCC.Core.CardOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("date");

                    b.Property<string>("ExpireDateFa")
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("ExpireDayNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasComment("\r\n                    1:اولیه \r\n                    2:تایید شده\r\n                    3:لغو شده ");

                    b.Property<int>("Tedad")
                        .HasColumnType("int");

                    b.Property<int?>("UserIdChanged")
                        .HasColumnType("int");

                    b.Property<int>("UserIdCreated")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("CardOrders");
                });

            modelBuilder.Entity("SematecCC.Core.CardTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("BranchId")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<int>("CardTransactionTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ProviderId")
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("RemainedAmount")
                        .HasColumnType("decimal(18,3)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasComment(" \r\n                1:اولیه\r\n                2:تایید شده \r\n                3:منقضی شده \r\n                4:مرجوع شده");

                    b.Property<string>("TerminalId")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UserIdChanged")
                        .HasColumnType("int");

                    b.Property<int>("UserIdCreated")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("CardTransactionTypeId");

                    b.HasIndex("ProviderId")
                        .HasDatabaseName("UX_CardTransaction_ProviderId");

                    b.ToTable("CardTransactions");
                });

            modelBuilder.Entity("SematecCC.Core.CardTransactionType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<short>("Sign")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UserIdChanged")
                        .HasColumnType("int");

                    b.Property<int>("UserIdCreated")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CardTransactionTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2026, 6, 14, 15, 44, 37, 285, DateTimeKind.Local).AddTicks(2366),
                            Sign = (short)1,
                            Title = "شارژ اولیه",
                            UserIdCreated = 1
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2026, 6, 14, 15, 44, 37, 285, DateTimeKind.Local).AddTicks(2369),
                            Sign = (short)-1,
                            Title = "خرج کردن",
                            UserIdCreated = 1
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2026, 6, 14, 15, 44, 37, 285, DateTimeKind.Local).AddTicks(2370),
                            Sign = (short)1,
                            Title = "افزایش دستی اعتبار کارت ",
                            UserIdCreated = 1
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2026, 6, 14, 15, 44, 37, 285, DateTimeKind.Local).AddTicks(2372),
                            Sign = (short)-1,
                            Title = "کاهش دستی اعتبار کارت ",
                            UserIdCreated = 1
                        },
                        new
                        {
                            Id = 5,
                            DateCreated = new DateTime(2026, 6, 14, 15, 44, 37, 285, DateTimeKind.Local).AddTicks(2374),
                            Sign = (short)1,
                            Title = "افزایش تراکنش لغو شده",
                            UserIdCreated = 1
                        },
                        new
                        {
                            Id = 6,
                            DateCreated = new DateTime(2026, 6, 14, 15, 44, 37, 285, DateTimeKind.Local).AddTicks(2375),
                            Sign = (short)1,
                            Title = "افزایش تراکنش منقضی شده",
                            UserIdCreated = 1
                        },
                        new
                        {
                            Id = 7,
                            DateCreated = new DateTime(2026, 6, 14, 15, 44, 37, 285, DateTimeKind.Local).AddTicks(2377),
                            Sign = (short)1,
                            Title = "افزایش اعتبار کارت از طریق Api",
                            UserIdCreated = 1
                        });
                });

            modelBuilder.Entity("SematecCC.Core.CardType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsChargeable")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UserIdChanged")
                        .HasColumnType("int");

                    b.Property<int>("UserIdCreated")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CardTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2026, 6, 14, 15, 44, 37, 285, DateTimeKind.Local).AddTicks(4138),
                            IsChargeable = false,
                            Title = "کارت هدیه",
                            UserIdCreated = 1
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2026, 6, 14, 15, 44, 37, 285, DateTimeKind.Local).AddTicks(4141),
                            IsChargeable = false,
                            Title = "کارت باشگاه مشتریان ",
                            UserIdCreated = 1
                        });
                });

            modelBuilder.Entity("SematecCC.Core.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiPassword")
                        .HasMaxLength(656)
                        .HasColumnType("nvarchar(656)");

                    b.Property<string>("ApiUsername")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ClientID")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("ClientSecret")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("UserIdChanged")
                        .HasColumnType("int");

                    b.Property<int>("UserIdCreated")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyCode")
                        .IsUnique()
                        .HasDatabaseName("IX_Companies_CompanyCode_Unique");

                    b.HasIndex("CompanyName")
                        .IsUnique()
                        .HasDatabaseName("IX_Companies_CompanyName_Unique");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyCode = "01307816",
                            CompanyName = "شرکت گیو",
                            DateCreated = new DateTime(2026, 6, 14, 15, 44, 37, 225, DateTimeKind.Local).AddTicks(2503),
                            UserIdCreated = 1
                        });
                });

            modelBuilder.Entity("SematecCC.Core.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("UserIdChanged")
                        .HasColumnType("int");

                    b.Property<int>("UserIdCreated")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Customers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2026, 6, 14, 15, 44, 37, 225, DateTimeKind.Local).AddTicks(2342),
                            FirstName = "مهران",
                            LastName = "صرافی",
                            NationalCode = "1234567890",
                            UserIdCreated = 1
                        });
                });

            modelBuilder.Entity("SematecCC.Core.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateDone")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<byte>("OperationId")
                        .HasColumnType("tinyint")
                        .HasComment("\r\n                        1:تایید سفارش کارت \r\n                        2:لغو سفارش کارت \r\n                        3:غیرفعال کردن کارت \r\n                        4:فعال کردن کارت \r\n                        5:تعیین مالک کارت \r\n                        6: افزایش دستی اعتبار کارت \r\n                        7: کاهش دستی اعتبار کارت \r\n                        ");

                    b.Property<int>("RecordId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("SematecCC.Core.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int?>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.ToTable("Menu");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Label = "صفحه نخست",
                            Name = "Home"
                        },
                        new
                        {
                            Id = 2,
                            Label = "مدیریت کاربران",
                            Name = "UserAccount",
                            PermissionId = 2
                        },
                        new
                        {
                            Id = 3,
                            Label = "مدیریت شرکت ها",
                            Name = "Companya",
                            PermissionId = 3
                        },
                        new
                        {
                            Id = 4,
                            Label = "مدیریت سازمان ها",
                            Name = "Organization",
                            PermissionId = 4
                        },
                        new
                        {
                            Id = 5,
                            Label = "مدیریت شخص ها",
                            Name = "Person",
                            PermissionId = 5
                        },
                        new
                        {
                            Id = 6,
                            Label = "مدیریت سفارش کارت ها",
                            Name = "CardOrder",
                            PermissionId = 6
                        },
                        new
                        {
                            Id = 7,
                            Label = "جستجوی کارت ها",
                            Name = "CardOrderDetailsView",
                            PermissionId = 30
                        },
                        new
                        {
                            Id = 20,
                            Label = "کاربر جدید",
                            Name = "UserAccountNew",
                            ParentId = 2,
                            PermissionId = 18
                        },
                        new
                        {
                            Id = 21,
                            Label = "کاربران",
                            Name = "UserAccountList",
                            ParentId = 2,
                            PermissionId = 19
                        },
                        new
                        {
                            Id = 22,
                            Label = "مجوزها",
                            Name = "UserAccountPermissions",
                            ParentId = 2,
                            PermissionId = 20
                        },
                        new
                        {
                            Id = 23,
                            Label = "شرکت جدید",
                            Name = "CompanyNew",
                            ParentId = 3,
                            PermissionId = 17
                        },
                        new
                        {
                            Id = 24,
                            Label = "شرکت ها",
                            Name = "CompanyList",
                            ParentId = 3,
                            PermissionId = 16
                        },
                        new
                        {
                            Id = 25,
                            Label = "سازمان جدید",
                            Name = "OrganizationNew",
                            ParentId = 4,
                            PermissionId = 23
                        },
                        new
                        {
                            Id = 26,
                            Label = "سازمان ها",
                            Name = "OrganizationList",
                            ParentId = 4,
                            PermissionId = 21
                        },
                        new
                        {
                            Id = 27,
                            Label = "شخص جدید",
                            Name = "PersonNew",
                            ParentId = 5,
                            PermissionId = 27
                        },
                        new
                        {
                            Id = 28,
                            Label = "شخص ها",
                            Name = "PersonList",
                            ParentId = 5,
                            PermissionId = 25
                        },
                        new
                        {
                            Id = 29,
                            Label = "سفارش کارت جدید",
                            Name = "CardOrderNew",
                            ParentId = 6,
                            PermissionId = 31
                        },
                        new
                        {
                            Id = 30,
                            Label = "سفارش کارت ها",
                            Name = "CardOrderList",
                            ParentId = 6,
                            PermissionId = 29
                        });
                });

            modelBuilder.Entity("SematecCC.Core.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Mobile")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telephone")
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("UserIdChanged")
                        .HasColumnType("int");

                    b.Property<int>("UserIdCreated")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationName")
                        .IsUnique()
                        .HasDatabaseName("UI_Organization_OrganizationName");

                    b.ToTable("Organizations", (string)null);
                });

            modelBuilder.Entity("SematecCC.Core.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Label = "مدیریت کاربران",
                            Name = "UserAccount"
                        },
                        new
                        {
                            Id = 3,
                            Label = "مدیریت شرکت ها",
                            Name = "Company"
                        },
                        new
                        {
                            Id = 4,
                            Label = "مدیریت سازمان ها",
                            Name = "Organization"
                        },
                        new
                        {
                            Id = 5,
                            Label = "مدیریت شخص ها",
                            Name = "Person"
                        },
                        new
                        {
                            Id = 6,
                            Label = "مدیریت سفارش کارت ها",
                            Name = "CardOrder"
                        },
                        new
                        {
                            Id = 16,
                            Label = "شرکت ها",
                            Name = "CompanyList",
                            ParentId = 3
                        },
                        new
                        {
                            Id = 17,
                            Label = "شرکت جدید",
                            Name = "CompanyNew",
                            ParentId = 3
                        },
                        new
                        {
                            Id = 18,
                            Label = "کاربر جدید",
                            Name = "UserAccountNew",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 19,
                            Label = "کاربران",
                            Name = "UserAccountList",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 20,
                            Label = "مجوزها",
                            Name = "UserAccountPermissions",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 21,
                            Label = " سازمان ها  ",
                            Name = "OrganizationList",
                            ParentId = 4
                        },
                        new
                        {
                            Id = 22,
                            Label = " مشاهده سازمان ها  ",
                            Name = "OrganizationView",
                            ParentId = 4
                        },
                        new
                        {
                            Id = 23,
                            Label = " سازمان جدید  ",
                            Name = "OrganizationNew",
                            ParentId = 4
                        },
                        new
                        {
                            Id = 24,
                            Label = "ویرایش سازمان",
                            Name = "OrganizationEdit",
                            ParentId = 4
                        },
                        new
                        {
                            Id = 25,
                            Label = "شخص ها",
                            Name = "PersonList",
                            ParentId = 5
                        },
                        new
                        {
                            Id = 26,
                            Label = "مشاهده شخص ها",
                            Name = "PersonView",
                            ParentId = 5
                        },
                        new
                        {
                            Id = 27,
                            Label = "شخص جدید",
                            Name = "PersonNew",
                            ParentId = 5
                        },
                        new
                        {
                            Id = 28,
                            Label = "ویرایش شخص",
                            Name = "PersonEdit",
                            ParentId = 5
                        },
                        new
                        {
                            Id = 29,
                            Label = "سفارش کارت ها",
                            Name = "CardOrderList",
                            ParentId = 6
                        },
                        new
                        {
                            Id = 30,
                            Label = "مشاهده جزییات سفارش کارت",
                            Name = "CardOrderDetailsView",
                            ParentId = 6
                        },
                        new
                        {
                            Id = 31,
                            Label = " سفارش کارت جدید",
                            Name = "CardOrderNew",
                            ParentId = 6
                        },
                        new
                        {
                            Id = 32,
                            Label = "ویرایش سفارش کارت",
                            Name = "CardOrderEdit",
                            ParentId = 6
                        },
                        new
                        {
                            Id = 33,
                            Label = " تایید سفارش کارت",
                            Name = "CardOrderConfirm",
                            ParentId = 6
                        },
                        new
                        {
                            Id = 34,
                            Label = " لغو سفارش کارت ها",
                            Name = "CardOrderCancel",
                            ParentId = 6
                        },
                        new
                        {
                            Id = 35,
                            Label = "فعال کردن سفارش کارت",
                            Name = "CardOrderEnable",
                            ParentId = 6
                        },
                        new
                        {
                            Id = 36,
                            Label = "غیر فعال کردن سفارش کارت",
                            Name = "CardOrderDisable",
                            ParentId = 6
                        },
                        new
                        {
                            Id = 37,
                            Label = "خروجی اکسل کارت ها ",
                            Name = "CardOrderSendToExcel",
                            ParentId = 30
                        },
                        new
                        {
                            Id = 38,
                            Label = " خروجی csv ",
                            Name = "CardOrderCSV",
                            ParentId = 30
                        },
                        new
                        {
                            Id = 40,
                            Label = " تعیین تاریخ اعتبار دسته جمعی کارت ها",
                            Name = "CardOrderSetAllCardsExpireDate",
                            ParentId = 30
                        },
                        new
                        {
                            Id = 41,
                            Label = " تعیین تاریخ اعتبار یک کارت",
                            Name = "CardOrderSetTheCardExpireDate",
                            ParentId = 30
                        },
                        new
                        {
                            Id = 42,
                            Label = "مشاهده تراکنش های کارت",
                            Name = "CardOrderViewTheCardTransactions",
                            ParentId = 30
                        },
                        new
                        {
                            Id = 43,
                            Label = "فعال کردن کارت",
                            Name = "CardOrderEnableTheCard",
                            ParentId = 30
                        },
                        new
                        {
                            Id = 44,
                            Label = "غیر فعال کردن کارت ",
                            Name = "CardOrderDisableTheCard",
                            ParentId = 30
                        },
                        new
                        {
                            Id = 45,
                            Label = "تعیین مالک کارت",
                            Name = "CardOrderSetOwnerOfTheCard",
                            ParentId = 30
                        },
                        new
                        {
                            Id = 46,
                            Label = "افزایش اعتبار کارت",
                            Name = "CardOrderIncreaseCreditOfTheCard",
                            ParentId = 30
                        },
                        new
                        {
                            Id = 47,
                            Label = "کاهش اعتبار کارت",
                            Name = "CardOrderDecreaseCreditOfTheCard",
                            ParentId = 30
                        });
                });

            modelBuilder.Entity("SematecCC.Core.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("BirthDateFa")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("GivId")
                        .HasColumnType("bigint")
                        .HasComment("UX_GivId_CompanyId: GivId is unique per company\nX_Company_Mobile: (GivId, CompanyId, Mobile) are indexed. For every company must be ONE Mobile registered and given one givId , but with api and offline data gathered its violation is possible.");

                    b.Property<string>("JobPlace")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NationalCode")
                        .HasColumnType("varchar(13)");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("UserIdChanged")
                        .HasColumnType("int");

                    b.Property<int>("UserIdCreated")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Mobile")
                        .HasDatabaseName("X_Company_Mobile");

                    b.HasIndex("GivId", "CompanyId")
                        .IsUnique()
                        .HasDatabaseName("UX_GivId_CompanyId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("SematecCC.Core.UserPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("SematecCC.Infra.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            Name = "companyAdmin",
                            NormalizedName = "COMPANYADMIN"
                        },
                        new
                        {
                            Id = 3,
                            Name = "companyUser",
                            NormalizedName = "COMPANYUser"
                        });
                });

            modelBuilder.Entity("SematecCC.Infra.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(656)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(656)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(656)");

                    b.Property<string>("Telephone")
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            CompanyId = 1,
                            ConcurrencyStamp = "e0933329-ac0b-4769-8812-985605640f20",
                            Email = "admin@givsoft.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LastName = "admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GIVSOFT.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEOP8vZhSSedXz/lLXJzNGe9NQ5QapaU2Aq+G6f0f+gRqqsln9lhslEvQDPWGZTglYw==",
                            PhoneNumber = "09121307816",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "0bc52e40-c3a2-49da-ad0d-5ccaa2b98872",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SematecCC.Core.Card", b =>
                {
                    b.HasOne("SematecCC.Core.CardOrder", "CardOrder")
                        .WithMany("Cards")
                        .HasForeignKey("CardOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SematecCC.Core.CardType", "CardType")
                        .WithMany()
                        .HasForeignKey("CardTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SematecCC.Core.Company", "Company")
                        .WithMany("Cards")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SematecCC.Core.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId");

                    b.HasOne("SematecCC.Core.Person", "Owner")
                        .WithMany("Cards")
                        .HasForeignKey("OwnerPersonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CardOrder");

                    b.Navigation("CardType");

                    b.Navigation("Company");

                    b.Navigation("Organization");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("SematecCC.Core.CardOrder", b =>
                {
                    b.HasOne("SematecCC.Core.Company", "Company")
                        .WithMany("CardOrders")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SematecCC.Core.Organization", "Organization")
                        .WithMany("CardOrders")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("SematecCC.Core.CardTransaction", b =>
                {
                    b.HasOne("SematecCC.Core.Card", "Card")
                        .WithMany("CardTransactions")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SematecCC.Core.CardTransactionType", "CardTransactionType")
                        .WithMany("CardTransactions")
                        .HasForeignKey("CardTransactionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("CardTransactionType");
                });

            modelBuilder.Entity("SematecCC.Core.Menu", b =>
                {
                    b.HasOne("SematecCC.Core.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("SematecCC.Core.Person", b =>
                {
                    b.HasOne("SematecCC.Core.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("SematecCC.Core.UserPermission", b =>
                {
                    b.HasOne("SematecCC.Core.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SematecCC.Infra.ApplicationUser", null)
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("SematecCC.Infra.ApplicationUser", b =>
                {
                    b.HasOne("SematecCC.Core.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("SematecCC.Infra.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("SematecCC.Infra.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("SematecCC.Infra.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("SematecCC.Infra.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SematecCC.Infra.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("SematecCC.Infra.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SematecCC.Core.Card", b =>
                {
                    b.Navigation("CardTransactions");
                });

            modelBuilder.Entity("SematecCC.Core.CardOrder", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("SematecCC.Core.CardTransactionType", b =>
                {
                    b.Navigation("CardTransactions");
                });

            modelBuilder.Entity("SematecCC.Core.Company", b =>
                {
                    b.Navigation("CardOrders");

                    b.Navigation("Cards");
                });

            modelBuilder.Entity("SematecCC.Core.Organization", b =>
                {
                    b.Navigation("CardOrders");
                });

            modelBuilder.Entity("SematecCC.Core.Person", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("SematecCC.Infra.ApplicationUser", b =>
                {
                    b.Navigation("UserPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
