<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace> SematecCC.Core</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Domain\Helpers\ToPersian().cs" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Application\DTO\ViewModels\" />
		<Folder Include="Application\Mappers\" />
		<Folder Include="Application\Validators\" />
		<Folder Include="Application\UseCases\" />
		<Folder Include="Domain\Exceptions\" />
	</ItemGroup>

	<ItemGroup>
		<None Include="Domain\Helpers\ToPersian%28%29.cs" />
	</ItemGroup>
	<ItemGroup>
		<Reference Include="EPPlus">
			<HintPath>Lib\EPPlus.dll</HintPath>
		</Reference>
	</ItemGroup>
	<ItemGroup>
		<Reference Include="Microsoft.IO.RecyclableMemoryStream">
			<HintPath>Lib\Microsoft.IO.RecyclableMemoryStream.dll</HintPath>
		</Reference>
	</ItemGroup>
	<ItemGroup>
		<Reference Include="EPPlus.System.Drawing">
			<HintPath>Lib\EPPlus.System.Drawing.dll</HintPath>
		</Reference>
	</ItemGroup>
	<ItemGroup>
		<Reference Include="EPPlus.Interfaces">
			<HintPath>Lib\EPPlus.Interfaces.dll</HintPath>
		</Reference>
	</ItemGroup>

</Project>
